### ISSUE TITLE
can't install on visual studio 2019

### ISSUE THREAD

**Issue by secreal** [nkahoang/VsFARMenu#2]
it was error
15/08/2019 00:24:45 - Install Error : Microsoft.VisualStudio.Setup.Dependencies.DependencyGraphConstructionException: The dependent package of 'Component.85caa711-8e6b-45a7-bc6c-afbc56605309,version=1.1' cannot be found: Microsoft.VisualStudio.Component.CoreEditor,version=[15.0,16.0).
   at Microsoft.VisualStudio.Setup.Engine.GetProductDependencyGraph(Product product, Boolean overwrite)
   at Microsoft.VisualStudio.ExtensionManager.SetupEngineService.get_GetProductDependencyGraph()
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

**Comment by yar3333** [comment]
Have the same error.
